config-version: 2
settings:
    language-file: lang-en.yml
    debug-mode: false
    update-checker: false
    web-address: https://hive.thehivemind.gay/forever/map
    web-directory:
        path: web
        auto-update: true
    image-quality:
        compress-images:
            enabled: false
            value: 0.0
    internal-webserver:
        enabled: false
        bind: 0.0.0.0
        port: 8080
        flush-json-immediately: false
    ui:
        coordinates:
            enabled: true
        link:
            enabled: true
        sidebar:
            pinned: pinned
    commands:
        main-command-label: squaremap
        main-command-aliases:
        - map
    render-progress-logging:
        enabled: true
        interval-seconds: 30
world-settings:
  default:
    map:
      enabled: true
      display-name: '{world}'
      # This number of JVM threads to use for rendering
      # (this is _not_ the same as cpu threads/cores)
      # use -1 to use half the available threads
      max-render-threads: -1
      # The background-render where automatic updates are
      # performed from triggered events
      background-render:
        # Enable this feature.
        enabled: true
        # The maximum amount of chunks to render from the queue at
        # time. Setting this too high may cause lag on your main
        # thread if the queue gets too large
        max-chunks-per-interval: 256
        # How often to check the queue for any chunks needing updates
        interval-seconds: 15
        # This number of JVM threads to use for background rendering
        # (this is _not_ the same as cpu threads/cores)
        # use -1 to use half of the available threads
        max-render-threads: -1
      # world markers
      markers:
        # how often to check for updates of the world markers
        update-interval-seconds: 360
        spawn-icon:
          enabled: true
          show-controls: true
          default-hidden: false
        world-border:
          enabled: false
    # player tracker settings
    player-tracker:
      enabled: false
      update-interval-seconds: 120
      show-controls: false
  minecraft:overworld:
    map:
      display-name: Overworld
  minecraft:the_nether:
    map:
      display-name: Nether
  minecraft:the_end:
    map:
      display-name: The End