hash-format = "sha256"

[[files]]
file = "config/amcdb.properties"
hash = "8ebd414bbea9412959280ee7f5163a2af942f0bacf64ad2eeb5e5584bae7094c"

[[files]]
file = "config/armorposer.toml"
hash = "3d722c9b0301d7b8766ac9ee1aa5ca52ad3a46012185a1db2fe348aece6534d3"

[[files]]
file = "config/cardinal-components-api.properties"
hash = "8d3ae8c9240fc60475fbb98a87b7e2e0874703b173a449fb346fb0857ada7bba"

[[files]]
file = "config/collective.json5"
hash = "ef2a4f3b28bf12df241cfaba733a4e96549909b2a91ff774da71c0e5c1bc4da4"

[[files]]
file = "config/deathbackup.json5"
hash = "9292dabe8b0a5a4b0118b4cacbd6a548234cb31d27e85e65d685fd1aaa414833"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "88e156ebea5860a21c27da03912948a7849f9dd0ba5c4ccc9c102f3c52208c81"

[[files]]
file = "config/moonrise.yml"
hash = "6221a70da7c057a8a44ed67b4c347200dd2a0a8bf7e68a3d8ace8b7a9306aaf7"

[[files]]
file = "config/noisium.json"
hash = "3b6acdbc5ce36d9a81fb2a889760b5eb9fd88683cb06e234eca92559ad151329"

[[files]]
file = "config/resourceful-config-web.json"
hash = "cf77cf1cb3809cebe552f1079dfeaca07cf409edc46f92df9686d7c8e843f9fc"

[[files]]
file = "config/structure_layout_optimizer.jsonc"
hash = "5a9058652bc0b88b8810e0b94eba0e1a90cbff2472845c53a7e67442682a1579"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fc8ffe66dc0c7eb55cf2ce38d1ae4bf1c4cdfbfdcda2636b1cd140c851e03cc5"
metafile = true

[[files]]
file = "mods/amcdb.pw.toml"
hash = "21ceb4ab833315e9a633516092c04d83217191a7541ad7fede38dd510d28b7f9"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "e68b724497f2a9ea4cead44c579f9acb128a9d5bbf7c198716c77b1f1cbbbe5c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "72f3dbfcfbf16d8437d865b090c4338cf32de86f290e8e8dde5626cb301bb4c7"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/death-backup.pw.toml"
hash = "6f5850283e6ef5c39c228d72e421e17dfe74082cfa2b501150783c99463406ef"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cf6edd71a012b437bca4bcac93c44d1109632db31b5f638d28b58fa77cf771b5"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "88a36b21d538d44aca7dd0a7e5ad8c09b1b263be3f4381e3bb22bc9f94ee7290"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "ec6cca86e9b3f9095b6b8fe66398618067cc23e5c273cfdb25dfb5263c7aeec6"
metafile = true

[[files]]
file = "mods/moonrise-opt.pw.toml"
hash = "2a61a08e39ea21bb9652683bf239345b04af91bf439c4ec60a6246b7cb37b9f4"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "c1906aafc5af2f95945d31f840263f3490efe781461fbcee33df3f3a68c431b3"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "d92bfa71e44d6ea1eff1e95955f776db2a3855c02b2d45ba98ef9a53913df485"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
hash = "072d663edf6434788b126994b7901a654efb279c4b7f503bcad4938d6d6396a5"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "424ba6f67a9392eb474ead2ea4ce5e3b6cc4f9041a4d27e61ad60a1abb009a50"
metafile = true

[[files]]
file = "resources/datapack/optional/amethyst/data/arc/advancement/amethyst.json"
hash = "89f65f4f05bad6285aee05f2af9c3cde52cbc0c40a6b59d001d18900d685cf41"

[[files]]
file = "resources/datapack/optional/amethyst/data/arc/recipe/amethyst_shards.json"
hash = "aa05f0867725ed84bbb5634789dc346165396f1c70d004824a388095b78ff1a7"

[[files]]
file = "resources/datapack/optional/amethyst/pack.mcmeta"
hash = "fa64b2d7a8a1eaaf669c02b24fe488d84558e3db75c2fd3422d56f97e58e5777"

[[files]]
file = "resources/datapack/optional/bundle/data/minecraft/advancement/recipes/tools/bundle.json"
hash = "c0427aa39217e52393a3c42a209f676f5151db0990acf6dcced180406baf803f"

[[files]]
file = "resources/datapack/optional/bundle/data/minecraft/recipe/bundle.json"
hash = "19e4bed6f87968000521570f66463fb866ea15f873ac96f807aebe67898efe4a"

[[files]]
file = "resources/datapack/optional/bundle/pack.mcmeta"
hash = "26aa411da73a991f8a85b1c8f5f7b954bb74377bf3e544ca5ff2615ced57186b"

[[files]]
file = "resources/datapack/optional/nyro_fixes/data/nyro/advancement/cobblestone.json"
hash = "cb46877cdc1e43c098a84fe45131c02d30043d6087ac535d192242fdb26be891"

[[files]]
file = "resources/datapack/optional/nyro_fixes/data/nyro/advancement/mangrove_log.json"
hash = "8c390544812d8c6c1eb4647be9319f4a5a33ebb6bf601565a5be4b17890e53d2"

[[files]]
file = "resources/datapack/optional/nyro_fixes/data/nyro/advancement/rooted_dirt.json"
hash = "3872e5b9fc0f34131faf74f8257e60e1dc9c2c805d57282beffd0137beb29a65"

[[files]]
file = "resources/datapack/optional/nyro_fixes/data/nyro/recipe/cobblestone.json"
hash = "9243bb0f6a0e6b0a1b69cc6a02de7fd376e0bfa8b89435258e00ca728ffdfb5d"

[[files]]
file = "resources/datapack/optional/nyro_fixes/data/nyro/recipe/mangrove_log.json"
hash = "bf85f30b2275c57cc878317836aa6f4abece457e354088a9befaadd29b58351c"

[[files]]
file = "resources/datapack/optional/nyro_fixes/data/nyro/recipe/rooted_dirt.json"
hash = "5ae8af8034773c65f6331b61b943c5071538c972a7853f4ef66914aca9edf20b"

[[files]]
file = "resources/datapack/optional/nyro_fixes/pack.mcmeta"
hash = "b46c6ba2f646c20be61ab9c2084a7d3db2f3bf190d8b727bd76fc53a3d40e1cd"

[[files]]
file = "resources/datapack/optional/phantom_membrane/data/arc/advancement/phantom_membrane.json"
hash = "f2337a1347e4666d486e84fa9b3c12bb23393e9139673cc00ad5e2da811380bd"

[[files]]
file = "resources/datapack/optional/phantom_membrane/data/arc/recipe/phantom_membrane.json"
hash = "6a7109ad73cb8f25c6d2f099cec7c49aa04d408c785dcba90b1e7295960858e7"

[[files]]
file = "resources/datapack/optional/phantom_membrane/pack.mcmeta"
hash = "fa64b2d7a8a1eaaf669c02b24fe488d84558e3db75c2fd3422d56f97e58e5777"

[[files]]
file = "resources/datapack/optional/saddle/data/arc/advancement/saddle.json"
hash = "e59a9e8ff6d9cfbac76f493b5231e22443fb14c0b4ad16f3fc54a58ff8d157b1"

[[files]]
file = "resources/datapack/optional/saddle/data/arc/recipe/saddle_recipe.json"
hash = "8d8f6d76b9c88a392dc365e45fd039a080de69d4e5a094b323cc48c7736c7a7e"

[[files]]
file = "resources/datapack/optional/saddle/pack.mcmeta"
hash = "f840a5c09a158985cdf62f284c819df2b9138a188f568d39c1bd664870a319cb"

[[files]]
file = "resources/datapack/optional/small_dripleaf/data/arc/advancement/dripleaf.json"
hash = "9b4149a76c7e202a0a37956f528ff8a9595c55ab63e16a230b750994f1832f37"

[[files]]
file = "resources/datapack/optional/small_dripleaf/data/arc/recipe/dripleaf_recipe.json"
hash = "b69f1839b237d73b0f2dc4c9a6adb5303af20632e60e6d4e4720b050dba40a4e"

[[files]]
file = "resources/datapack/optional/small_dripleaf/pack.mcmeta"
hash = "183b44ba15f757e5f5da35fc36b1f41a3459ac9b1ac8bf8cc7dfc5c31cd6764c"

[[files]]
file = "resources/datapack/optional/smelt_flesh/data/arc/advancement/smelt_flesh.json"
hash = "50def667931532e12eb25bc7b5711ff694b9bae0ad48a0c50b9ff01cca4e81b1"

[[files]]
file = "resources/datapack/optional/smelt_flesh/data/arc/recipe/smelt_flesh.json"
hash = "f7c68a0f0c9bf8e2c908b346315f386f872ddc88c4a09eb43a21f2f664678cf2"

[[files]]
file = "resources/datapack/optional/smelt_flesh/pack.mcmeta"
hash = "ca4c1b1c27ae2059ac9957fa97ddd8c6bb1236247dd4275b4ec119833082ce8a"

[[files]]
file = "resources/datapack/optional/trident/data/arc/advancement/trident.json"
hash = "e235422a9007b624a60b1d36cbbd8bcd745a11a932a73c1cceb6bf713cdb4351"

[[files]]
file = "resources/datapack/optional/trident/data/arc/recipe/trident_recipe.json"
hash = "d21f3b181bc0a142e4e566fe502f8adfa2966891c72b5a9873c64135b3af4ccc"

[[files]]
file = "resources/datapack/optional/trident/pack.mcmeta"
hash = "e41a97df90a902396713f0070da80c987e24aab48a329a677e22aa500bb9baca"

[[files]]
file = "resources/datapack/optional/vanilla_overrides/data/minecraft/recipe/dispenser.json"
hash = "ef1722898e8ba0660c455d1e15ca9048eadd2f38deeb9dc9cdac3422f4949b1a"

[[files]]
file = "resources/datapack/optional/vanilla_overrides/data/minecraft/recipe/dropper.json"
hash = "56042355853b933cb57fcee58f5a34d47c6ba93b9e8357e3761dac561c6fad2a"

[[files]]
file = "resources/datapack/optional/vanilla_overrides/data/minecraft/recipe/lever.json"
hash = "5897e5260ff8c94db6e845ab261b6817b4ffa31ceaf1d53a8de160f17ae470bf"

[[files]]
file = "resources/datapack/optional/vanilla_overrides/data/minecraft/tags/item/stone_crafting_materials.json"
hash = "ef877f92d90fbdf895129ec6f494e6c1b3c766f1c3b81f161de4c51a5567054b"

[[files]]
file = "resources/datapack/optional/vanilla_overrides/data/minecraft/tags/item/stone_tool_materials.json"
hash = "465b833d72a5e8a25dc1646e0e0374da07940dbb1b82b22ebf29d9c12a4207ce"

[[files]]
file = "resources/datapack/optional/vanilla_overrides/pack.mcmeta"
hash = "8d2dc960220aae89e4c8143992514c7d3d056e0614d6bdb99241a194633f9fd3"

[[files]]
file = "resources/datapack/optional/wool2string/data/arc/advancement/string_from_wool.json"
hash = "d2b64546a5a9433eeb8f6a72b7ba7b19ddb99d551764c37d2a4f811923cfe3e7"

[[files]]
file = "resources/datapack/optional/wool2string/data/arc/recipe/string_recipe.json"
hash = "e353f8a975d3ae7e140a71c03d8a5839e36488d613c031ee002de92fd9ab3179"

[[files]]
file = "resources/datapack/optional/wool2string/pack.mcmeta"
hash = "a87418be1a5611c62edf77b7c7a9890783c02ca248cd2c0ae01572c12b60e97f"
