name = "THM Forever Server Mods"
author = "ArcOnyx"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8621c8361fd55eaf7cc9a1136c3b5af9a4c1a5c7639789179afdf31723e53577"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
datapack-folder = "resources/datapack"
