name = "THM Forever Server Mods"
author = "ArcOnyx"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bf91a6a9a9990b78b49063c7aa2a5efc6f15e7c28b79c7a3155e16509875084"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
datapack-folder = "resources/datapack"
