[general]
enableConfigGui = true
enableNameTags = true
allowScrolling = true
restrictResizeToOP = false
nameBasedFeatures = false
resizeWhitelist = []
[client]
directNametagOnly = false
nametagRenderDistance = 0
