name: Packwiz refresh

on:
  push:
    paths: 
      - 'hosts/hive/minecraft/servers/forever/packwiz/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Nix Quick Install
        uses: nixbuild/nix-quick-install-action@v34

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
            primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}-packwiz-${{ hashFiles('hosts/hive/minecraft/servers/forever/packwiz/pack.toml') }}
            restore-prefixes-first-match: |
              nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}-packwiz-
              nix-${{ runner.os }}-

      - name: Run packwiz refresh
        run: |
            cd hosts/hive/minecraft/servers/forever/packwiz
            nix develop --command packwiz refresh

      - name: Commit any changes
        run: |
            if [[ `git status --porcelain` ]]; then
              echo "Packwiz hash has changed. Packwiz must be refreshed and the nix FOD hash updated."
              echo "Calculating nix FOD hash"
              nix build .#forever-modpack
              echo "Please apply changes manually"
              exit 1
            else
              echo "No changes"
              exit 0
            fi
      
